services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9679:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    profiles:
      - postgres
    env_file:
      - .env
    volumes:
      - postgres_data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file:
      - .env
    restart: unless-stopped

networks:
  default:
    name: cu-roadmap

volumes:
  postgres_data:
